import NavBar from "@/components/NavBar";
import "./globals.css";
import Footer from "@/components/Footer";

export const metadata = {
  title: "Mohammad R. Prince",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className=" bg-[#000000] selection:bg-white selection:text-black mt-20 ">
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
